import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {createLocalDB} from './local-db.mjs';
import worker from '../dist/server/index.js';
import {digest} from '../worker/bridge.js';
import {createGateway} from '../api/gateway.js';
const db=createLocalDB(':memory:',fileURLToPath(new URL('../drizzle',import.meta.url)));
const origin='https://viperr-archive.vercel.app', backend='https://viperr-archive.adilzhanaliakbar.chatgpt.site';
const env={DB:db,VIPERR_PUBLIC_ORIGIN:origin,ASSETS:{fetch:()=>new Response('static')}};
let checks=0,upstreamCalls=0;
const eq=(a,b)=>{assert.deepEqual(a,b);checks++;};
const gateway=createGateway({origin,fetchUpstream:async(url,options)=>{upstreamCalls++;return worker.fetch(new Request(url,options),env);}});
const req=(path,options={})=>gateway(new Request(origin+path,options));
const native=(path,options={})=>worker.fetch(new Request(backend+path,options),env);
const mutation=(cookie,body)=>({method:'POST',headers:{Origin:origin,'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify(body)});
try{
 eq(await digest('dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk'),'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM');
 const anon=await(await req('/api/state',{headers:{'oai-authenticated-user-id':'spoof',Authorization:'Bearer fake'}})).json();
 eq(anon.authenticated,false);eq(anon.signInPath,'/api/auth/start');
 const started=await req('/api/auth/start?return_to='+encodeURIComponent('/?playlist=demo#discography'));
 eq(started.status,302);assert(started.headers.get('set-cookie').includes('Secure; HttpOnly; SameSite=Lax'));checks++;
 const flowCookie=started.headers.get('set-cookie').split(';')[0];
 const authorization=new URL(started.headers.get('location'));
 const noUser=await native(authorization.pathname+authorization.search);eq(new URL(noUser.headers.get('location'),backend).pathname,'/signin-with-chatgpt');
 const issued=await native(authorization.pathname+authorization.search,{headers:{'oai-authenticated-user-id':'existing-listener'}});
 const callback=new URL(issued.headers.get('location'));eq(callback.origin,origin);
 const code=callback.searchParams.get('code'),state=callback.searchParams.get('state');
 const flow=JSON.parse(Buffer.from(flowCookie.split('=')[1],'base64url').toString());
 const exchange=(extra={})=>native('/api/auth/exchange',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,state,verifier:flow.verifier,redirect_uri:origin+'/api/auth/callback',...extra})});
 eq((await exchange({verifier:'x'.repeat(43)})).status,401);
 eq((await exchange({state:'y'.repeat(43)})).status,401);
 eq((await exchange({redirect_uri:'https://attacker.test/api/auth/callback'})).status,400);
 eq((await req(callback.pathname+callback.search.replace(state,'z'.repeat(43)),{headers:{Cookie:flowCookie}})).status,401);
 const responses=await Promise.all([req(callback.pathname+callback.search,{headers:{Cookie:flowCookie}}),req(callback.pathname+callback.search,{headers:{Cookie:flowCookie}})]);
 eq(responses.map(r=>r.status).sort(),[302,401]);
 const signed=responses.find(r=>r.status===302);eq(signed.headers.get('location'),origin+'/?playlist=demo#discography');
 const sessionCookie=signed.headers.getSetCookie().find(c=>c.startsWith('__Host-viperr-session=')).split(';')[0];
 const token=sessionCookie.split('=')[1];eq((await exchange()).status,401);
 const stored=await db.prepare('SELECT token_hash FROM bridge_sessions').first();eq(stored.token_hash,await digest(token));eq(stored.token_hash===token,false);
 const save=await req('/api/saved',{...mutation(sessionCookie,{add:['heavy-metal']}),method:'PATCH'});eq(save.status,200);
 const originalState=await(await native('/api/state',{headers:{'oai-authenticated-user-id':'existing-listener'}})).json();eq(originalState.saved,['heavy-metal']);
 const userState=await(await req('/api/state',{headers:{Cookie:sessionCookie,'oai-authenticated-user-id':'another-listener'}})).json();eq(userState.saved,['heavy-metal']);eq(userState.authenticated,true);
 const calls=upstreamCalls;eq((await req('/api/vote',{...mutation(sessionCookie,{albumId:'heavy-metal'}),headers:{Origin:'https://evil.test',Cookie:sessionCookie,'Content-Type':'application/json'}})).status,403);eq(upstreamCalls,calls);
 eq((await req('/api/vote',{...mutation(sessionCookie,{albumId:'heavy-metal'}),headers:{Cookie:sessionCookie,'Content-Type':'application/json'}})).status,403);
 eq((await req('/api/vote',mutation(sessionCookie,{albumId:'heavy-metal'}))).status,200);
 eq((await req('/api/saved',{...mutation(sessionCookie,{}),body:'x'.repeat(9000),method:'PATCH'})).status,413);
 eq((await req('/api/auth/exchange',mutation(sessionCookie,{}))).status,404);
 eq((await gateway(new Request('https://fake.vercel.app/api/auth/start'))).status,403);
 eq((await req('/api/auth/start?return_to=//evil.test')).status,302);
 eq((await req('/api/auth/callback?state=a&state=b')).status,400);
 const forged=await(await native('/api/state',{headers:{Authorization:'Bearer '+'z'.repeat(43),'oai-authenticated-user-id':'existing-listener'}})).json();eq(forged.authenticated,false);
 await db.prepare('UPDATE bridge_sessions SET expires_at = ?').bind(Date.now()-1).run();
 eq((await(await req('/api/state',{headers:{Cookie:sessionCookie}})).json()).authenticated,false);
 await db.prepare('UPDATE bridge_sessions SET expires_at = ?').bind(Date.now()+100000).run();
 eq((await req('/api/auth/logout',mutation(sessionCookie,{}))).status,200);
 eq((await(await req('/api/state',{headers:{Cookie:sessionCookie}})).json()).authenticated,false);
 const expiredCode=await native(authorization.pathname+authorization.search,{headers:{'oai-authenticated-user-id':'existing-listener'}});
 await db.prepare('UPDATE bridge_codes SET expires_at = ?').bind(Date.now()-1).run();
 eq((await exchange({code:new URL(expiredCode.headers.get('location')).searchParams.get('code')})).status,401);
 eq((await native('/auth/bridge?state='+state+'&code_challenge='+flow.verifier+'&code_challenge_method=plain')).status,400);
 console.log(`Passed ${checks} bridge checks: PKCE, replay, session ownership, expiry, CSRF, logout and shared data.`);
}finally{db.close();}
