import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {createLocalDB} from './local-db.mjs';
import worker from '../dist/server/index.js';
const db=createLocalDB(':memory:',fileURLToPath(new URL('../drizzle',import.meta.url)));
const env={DB:db,ASSETS:{fetch:()=>new Response('static')}};
const first='heavy-metal',second='heavy-metal-2';let checks=0;
async function call(path,method='GET',body,identity='listener-a',extra={}){const headers={'content-type':'application/json',origin:'https://viperr.test',...extra};if(identity)headers['oai-authenticated-user-id']=identity;const res=await worker.fetch(new Request('https://viperr.test'+path,{method,headers,...(body!==undefined?{body:typeof body==='string'?body:JSON.stringify(body)}:{})}),env);return {status:res.status,body:await res.json()};}
const eq=(actual,expected)=>{assert.deepEqual(actual,expected);checks++;};
try{
 eq((await call('/api/state')).body.saved,[]);
 eq((await call('/api/state','GET',undefined,null)).body.authenticated,false);
 eq((await call('/api/state','GET',undefined,null)).body.saved,[]);
 eq((await call('/api/saved','PUT',{ids:[first,first,second]})).body.saved,[first,second]);
 eq((await call('/api/state')).body.saved,[first,second]);
 eq((await call('/api/state','GET',undefined,'listener-b')).body.saved,[]);
 eq((await call('/api/saved','PUT',{ids:['fake-album']})).status,400);
 eq((await call('/api/saved','PUT',{ids:[]} ,null)).status,401);
 eq((await call('/api/saved','PUT',{ids:[]},'listener-a',{origin:'https://other.test'})).status,403);
 eq((await call('/api/saved','PUT','{bad')).status,400);
 eq((await call('/api/saved','PUT','x'.repeat(9000))).status,413);
 await Promise.all([call('/api/saved','PATCH',{add:[first]},'listener-c'),call('/api/saved','PATCH',{add:[second]},'listener-c')]);
 eq((await call('/api/state','GET',undefined,'listener-c')).body.saved.sort(),[first,second].sort());
 eq((await call('/api/saved','PATCH',{remove:[first]},'listener-c')).body.saved,[second]);
 eq((await call('/api/vote','POST',{albumId:first})).body.stats,[{albumId:first,votes:1}]);
 eq((await call('/api/vote','POST',{albumId:first})).body.stats,[{albumId:first,votes:1}]);
 eq((await call('/api/vote','POST',{albumId:second})).body.stats,[{albumId:second,votes:1}]);
 eq((await call('/api/vote','POST',{albumId:second},'listener-b')).body.stats,[{albumId:second,votes:2}]);
 eq((await call('/api/state')).body.vote,second);
 const id=crypto.randomUUID(),payload={id,title:'Shared frequency',ids:[second,first]};
 const created=await call('/api/playlists','POST',payload);eq(created.status,201);eq(created.body.ids,[second,first]);
 eq((await call('/api/playlists','POST',payload)).status,200);
 eq((await call('/api/state')).body.playlistCount,1);
 const shared=await call('/api/playlists/'+id,'GET',undefined,'listener-b');eq(shared.body.title,payload.title);eq(shared.body.ids,[second,first]);eq('ownerId' in shared.body,false);
 eq((await call('/api/playlists/'+id,'GET',undefined,null)).body.ids,[second,first]);
 eq((await call('/api/vote','POST',{albumId:first},null)).status,401);
 eq((await call('/api/playlists','POST',{title:'Anonymous',ids:[first]},null)).status,401);
 eq((await call('/api/playlists','POST',payload,'listener-b')).status,409);
 const parallelPayload={id:crypto.randomUUID(),title:'Concurrent retry',ids:[first]};
 const parallel=await Promise.all([call('/api/playlists','POST',parallelPayload,'listener-c'),call('/api/playlists','POST',parallelPayload,'listener-c')]);
 eq(parallel.map(r=>r.status).sort(),[200,201]);
 eq((await call('/api/playlists','POST',{title:'Empty',ids:[]})).status,400);
 eq((await call('/api/playlists/'+crypto.randomUUID())).status,404);
 eq((await call('/api/state','POST',{})).status,405);
 for(let i=0;i<19;i++)eq((await call('/api/playlists','POST',{title:'Frequency '+i,ids:[first]})).status,201);
 eq((await call('/api/playlists','POST',{title:'Rate limited',ids:[first]})).status,429);
 eq(await (await worker.fetch(new Request('https://viperr.test/'),env)).text(),'static');
 console.log(`${checks} API assertions passed: ownership, persistence, vote changes, shared links, input validation and limits.`);
}finally{db.close();}
